name: GitHub Activity Tracker

on:
  schedule:
    - cron: '0 */12 * * *'  # Ejecuta cada 12 horas
  workflow_dispatch:  # Permite que se ejecute manualmente

jobs:
  activity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch GitHub Activity
        env:
          GH_PAT: ${{ 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 }}  # Tu token almacenado como secreto
        run: |
          curl -H "Authorization: token $GH_PAT" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/users/Pastu17/events > activity.json

      - name: Extract Recent Activity
        run: |
          cat activity.json | jq '.[] | select(.type == "PushEvent") | .repo.name, .payload.commits[] | .message' > recent_activity.txt
          
      - name: Update README with Recent Activity
        run: |
          recent_activity=$(cat recent_activity.txt)
          sed -i "/## ⚡ Recent GitHub Activity/a\\n<p align=\"center\">\\n$recent_activity\\n</p>" README.md

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Updated recent GitHub activity"
          git push
