name: Recent Activity

on:
  schedule:
    - cron: '*/30 * * * *' # Ejecuta cada 30 minutos
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Recent Activity
        uses: jamesgeorge007/github-activity-readme@v1.0.0
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Push Changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update README with recent activity"
          git push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
